# .streamlit/secrets.toml

# Supabase Database Credentials
db_host = "aws-1-ap-south-1.pooler.supabase.com"
db_name = "postgres"
db_user = "postgres.jbdaxjpovpmrkmsazxgw"
db_password = "thevalk3"
db_port = "6543"

# Google Gemini API Key
google_api_key = "AIzaSyAf8mF5mXWhMXb8IIVgnoJjH40j-vTD2AI"